### PR TITLE
Address #34.

### LINKED ISSUE #34: Guard against NULL issue in default mapper
It's in or around
```objc
        Class managedObjectClass = objc_getClass(className);
        objc_property_t prop = class_getProperty(managedObjectClass, propertyName);

        NSString *attributeString = [NSString stringWithCString:property_getAttributes(prop) encoding:NSUTF8StringEncoding];
```
in `expectedClassForObject:andKey:`.  (I think it's that `prop` is `NULL` and then `property_getAttributes(prop)` crashes.)

### PR DESCRIPTION
**Pull request by vokal-isaac**
Resolves #34.

Avoid production crashes with additional safety around failure to get a property and/or failure to get a class.  (Programmer-error cases are already covered by assertions.)

Since @chillpop said he was going to version-bump in a subsequent PR, I didn't touch the version and didn't `pod update` in either sample project.

@vokal/ios-developers Code review please?

### CODE REVIEW

**Comment by designatednerd** [comment]
For context: #34

File: Pod/Classes/VOKManagedObjectMapper.m [hunk 1]
```diff
@@ -156,6 +156,10 @@ - (id)checkString:(id)outputObject withDateFormatter:(NSDateFormatter *)dateForm
 - (id)checkClass:(id)inputObject managedObject:(NSManagedObject *)object key:(NSString *)key
 {
     Class expectedClass = [self expectedClassForObject:object andKey:key];
+    if (!expectedClass) {
+        VOK_CDLog(@"Failed to get class for %@\nProperty: %@", object, key);
+        return nil;
```
Comment (designatednerd) [inline Pod/Classes/VOKManagedObjectMapper.m]: Should this also return `Nil`? And should we explicitly be returning a `Class` rather than an `id` if that's the case?

Comment (vokal-isaac) [inline Pod/Classes/VOKManagedObjectMapper.m]: `checkClass:managedObject:key:` returns `inputObject` on success and `nil` on failure, so `id` and `nil` are correct.

Comment (designatednerd) [inline Pod/Classes/VOKManagedObjectMapper.m]: in that case, should it be `nil` instead of `Nil` below?

Comment (vokal-isaac) [inline Pod/Classes/VOKManagedObjectMapper.m]: Nope, that's in `- (Class)expectedClassForObject:(NSManagedObject *)object andKey:(id)key`

Comment (designatednerd) [inline Pod/Classes/VOKManagedObjectMapper.m]: ahhhhh derp, right. Thank you!

**Comment by designatednerd** [comment]
( :goat: , :goat: , :goat: )

**Comment by chillpop** [comment]
LGTM
